### ISSUE TITLE
We've incorrectly labeled a Maker `mint` function an event and should update the name

### ISSUE THREAD

**Issue by askeluv** [blockchain-etl/ethereum-etl-airflow#106]
[This table description](https://github.com/blockchain-etl/ethereum-etl-airflow/blob/master/dags/resources/stages/parse/table_definitions/maker/Dai_call_mint.json) uses `_event_` instead of `_call_`. This should be fixed - perhaps we also need to re-run the jobs for the historical data?

**Comment by medvedev1088** [comment]
Fixed now.
