### ISSUE TITLE
Chainlink parsing pointed at the wrong contracts

### ISSUE THREAD

**Issue by jdmaturen** [blockchain-etl/ethereum-etl-airflow#271]
Here is the current ETH/USD Answer Updated address:

https://github.com/blockchain-etl/ethereum-etl-airflow/blob/079975dee6df20692c8b70cd4f246317eacce643/dags/resources/stages/parse/table_definitions/chainlink/Aggregator_ETH_USD_event_AnswerUpdated.json#L20

However the [Chainlink Price Feeds documentation](https://docs.chain.link/docs/ethereum-addresses/#Ethereum%20Mainnet) points at [0xb022E2970b3501d8d83eD07912330d178543C1eB](https://etherscan.io/address/0xb022E2970b3501d8d83eD07912330d178543C1eB) which proxies to the aggregator [0xb95188f011e49a60fc6c743b1bc93b38651a204e](https://etherscan.io/address/0xb95188f011e49a60fc6c743b1bc93b38651a204e)

---

[0x79febf6b9f76853edbcbc913e6aae8232cfb9de9](https://etherscan.io/address/0x79febf6b9f76853edbcbc913e6aae8232cfb9de9) was last used roughly May 11 2020 (shortly after this code was merged)

![image](https://user-images.githubusercontent.com/70791/127710324-3b9db1cc-85ee-44b0-82e6-1a5c89336872.png)

Which is consistent when data was last reported in blockchain-etl: 

![image](https://user-images.githubusercontent.com/70791/127710385-6ca735b2-6c8f-4a80-afea-b3de00c55351.png)

--- 

I'm not sure which other events are also stale but spot checking a few most seemed to point to old contracts. I will see if anyone from the Chainlink community is interested in fixing this.

**Comment by medvedev1088** [comment]
Thanks for looking into this! Feel free to create a PR to fix it

**Comment by jdmaturen** [comment]
Will do! My only concern is that the underlying aggregator contract may change again at some point but we can figure out a long term solution later.
