### ISSUE TITLE
composer-1.8.3-airflow-1.10.3 not exist

### ISSUE THREAD

**Issue by wuminzhe** [blockchain-etl/ethereum-etl-airflow#300]
I follow the readme, the image version `composer-1.8.3-airflow-1.10.3` does not exist.
If I change it to another version, there will be other errors.

**Comment by medvedev1088** [comment]
There is a PR to fix this here https://github.com/blockchain-etl/ethereum-etl-airflow/pull/272 which will be merged later

**Comment by wuminzhe** [comment]
thanks for your PR
