### ISSUE TITLE
Make parsed logs real-time

### ISSUE THREAD

**Issue by medvedev1088** [blockchain-etl/ethereum-etl-airflow#80]
All datasets in `blockchain-etl.*` in BigQuery are updated daily currently. We can make them real-time by stitching historical and latest data parts as follows:

1. `<dataset>_internal.<table_name>_history` table containing historical data and updated daily.
2. `<dataset>_internal.<table_name>_live` view that parses data from the logs table and returns both historical and latest data.
3. `<dataset>.<table_name>` view is created that stitches `<dataset>_parts.<table_name>_history` and `<dataset>_parts.<table_name>_live` together, which contains both historical and latest data:

```
select * from <dataset>_internal.<table_name>_history` where block_timestamp <= <previous_day>
union all
select * from <dataset>_internal.<table_name>_live` where block_timestamp > <previous_day>
```

**Comment by chweeee** [comment]
May I know where in the codebase is the `<dataset>_internal.<table_name>_history` table created?

I got the following error when running the `parse_<dataset>_dag` on airflow.

`google.api_core.exceptions.NotFound: 404 Not found: Table <project_id>:ethereum_bancor.BancorNetwork_event_FlashLoanCompleted_history was not found in location US`

But I can't seem to find the code that initialises the table.
